### ISSUE TITLE
Grid for layout

### ISSUE THREAD

**Issue by C-G-G** [C-G-G/no-sketch-no-grid#1]
[grid-for-layout.pdf](https://github.com/C-G-G/no-sketch-no-grid/files/6004738/grid-for-layout.pdf)

@thomasjbradley

**Comment by thomasjbradley** [comment]
`<div>` for the banner does make sense—I don’t think there’s anything more specific.

I really like the use of an `<article>` tag for each Wonder. An alternative approach would be a `<figure>` & `<figcaption>` because the image is being described by that content.
